export const SEARCH_HOTELS_REQUEST = 'SEARCH_HOTELS_REQUEST';
export const SEARCH_HOTELS_SUCCESS = 'SEARCH_HOTELS_SUCCESS';
export const SEARCH_HOTELS_FAILURE = 'SEARCH_HOTELS_FAILURE';
export const SEARCH_HOTELS_CANCEL = 'SEARCH_HOTELS_CANCEL';

export const BOOKMARK_HOTEL = 'BOOKMARK_HOTEL';
export const UNBOOKMARK_HOTEL = 'UNBOOKMARK_HOTEL';

export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';


